name = "PyNNTraining"
uuid = "013e1a4a-88fe-473f-be94-6c6af62e62ad"
authors = ["lorenzoh <lorenz.ohly@gmail.com> and contributors"]
version = "0.1.0"

[deps]
FluxTraining = "7bf95e4d-ca32-48da-9824-f0dc5310474f"
PyCallChainRules = "b12ccfe2-7326-416f-9f4f-cd3183bd9fe8"

[compat]
julia = "1"
FluxTraining = "0.3"
PyCallChainRules = "0.4"
